baseURL = 'https://zweerts.xyz'
title = 'ZWEERTS.xyz'
author = 'Koen Zweerts'
languageCode = 'en-US'
copyright = 'Take what you need.'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  [params.author]
    name = 'Koen Zweerts'
