baseURL = 'https://zweerts.xyz/'
languageCode = 'en-us'
title = 'ZWEERTS.xyz'
author = 'Koen Zweerts'
copyright = 'Copyright, ZWEERTS.xyz'

[taxonomies]
  wiki = 'wikis'
  tag = 'tags'

[params]
  favicon = ''
  [params.author]
    email = 'koen@zweerts.xyz'
    name = 'Koen Zweerts'
